# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dzfy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fgxx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('cbr', models.CharField(max_length=20, verbose_name='承办人')),
                ('lxdh', models.CharField(max_length=11, null=True, verbose_name='联系电话')),
                ('bgjl', models.TextField(null=True, verbose_name='变更记录')),
            ],
            options={
                'verbose_name': '法官信息',
                'verbose_name_plural': '法官信息',
            },
        ),
        migrations.CreateModel(
            name='Wzxx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wid', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('bt', models.CharField(max_length=200, verbose_name='标题')),
                ('fbr', models.CharField(max_length=10, verbose_name='发布人')),
                ('fbsj', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('nr', models.TextField(verbose_name='内容')),
                ('fymc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dzfy.Fyxx', verbose_name='法院名称')),
                ('wzlx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dzfy.Wzlx', verbose_name='文章类型')),
            ],
            options={
                'ordering': ['-fbsj'],
                'verbose_name': '新闻/指南管理',
                'verbose_name_plural': '新闻/指南管理',
            },
        ),
    ]
