# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fgxx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.CharField(default='c55868cee11549a69371036b5c4e2c1f', max_length=100, unique=True)),
                ('cbr', models.CharField(max_length=20, verbose_name='承办人')),
                ('lxdh', models.CharField(max_length=11, null=True, verbose_name='联系电话')),
                ('bgjl', models.TextField(null=True, verbose_name='变更记录')),
            ],
            options={
                'verbose_name_plural': '法官信息',
                'verbose_name': '法官信息',
            },
        ),
    ]
