# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxgk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fgxx',
            name='fid',
            field=models.CharField(default='4341d747e748480fbadf2cec47ae8cd5', max_length=100, unique=True),
        ),
    ]
