# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxgk', '0002_auto_20160913_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fgxx',
            name='fid',
            field=models.CharField(default='145ab80649624d70a7223a45fcbe5c15', max_length=100),
        ),
    ]
