# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxgk', '0003_auto_20160913_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wzxx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wid', models.CharField(default='4654ef3395c647df9ad8480663b95304', max_length=100)),
                ('fymc', models.IntegerField(choices=[(1, '达州市中级人民法院'), (2, '开源法院')], verbose_name='法院名称')),
                ('wzlx', models.IntegerField(choices=[(1, '执行动态'), (2, '法律法规')], verbose_name='文章类型')),
                ('bt', models.CharField(max_length=200, verbose_name='标题')),
                ('fbr', models.CharField(max_length=10, verbose_name='发布人')),
                ('fbsj', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('nr', models.TextField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '文章管理',
                'verbose_name_plural': '文章管理',
                'ordering': ['-fbsj'],
            },
        ),
        migrations.AlterField(
            model_name='fgxx',
            name='fid',
            field=models.CharField(default='3e11e61ca3d04fa6b4b1af7e3f81fecf', max_length=100),
        ),
    ]
