# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxgk', '0004_auto_20160913_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fgxx',
            name='fid',
            field=models.CharField(default='99f525278c2440f49839072f8f989a7e', max_length=100),
        ),
        migrations.AlterField(
            model_name='wzxx',
            name='fymc',
            field=models.CharField(choices=[('达州市中级人民法院', '达州市中级人民法院'), ('开源法院', '开源法院')], max_length=50, verbose_name='法院名称'),
        ),
        migrations.AlterField(
            model_name='wzxx',
            name='wid',
            field=models.CharField(default='d2efa4a5e244401eb2fdaed2ca7ced5c', max_length=100),
        ),
        migrations.AlterField(
            model_name='wzxx',
            name='wzlx',
            field=models.CharField(choices=[('执行动态', '执行动态'), ('法律法规', '法律法规')], max_length=30, verbose_name='文章类型'),
        ),
    ]
