# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zxgk', '0006_auto_20160914_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fgxx',
            name='fid',
            field=models.CharField(default='1aa6da3c23f84f8bbfd1908e123b4bb5', max_length=100),
        ),
        migrations.AlterField(
            model_name='wzxx',
            name='fymc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dzfy.Fyxx', verbose_name='法院名称'),
        ),
        migrations.AlterField(
            model_name='wzxx',
            name='wid',
            field=models.CharField(default='0c184bbf759f419c8a1fd0ee116d2410', max_length=100),
        ),
        migrations.AlterField(
            model_name='wzxx',
            name='wzlx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dzfy.Wzlx', verbose_name='文章类型'),
        ),
    ]
