# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxgk', '0007_auto_20160914_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fgxx',
            name='fid',
            field=models.CharField(default='941a81911c4f4c12aab0f5d5d8c87d2b', max_length=100),
        ),
        migrations.AlterField(
            model_name='wzxx',
            name='wid',
            field=models.CharField(default='8b2dc863c1fb46f29a9de19c6666c8b5', max_length=100),
        ),
    ]
