# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ajxx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpws',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('fymc', models.CharField(max_length=50, verbose_name='法院名称')),
                ('bt', models.CharField(max_length=200, verbose_name='标题')),
                ('fbr', models.CharField(max_length=10, verbose_name='发布人')),
                ('fbsj', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('nr', models.TextField(verbose_name='内容')),
                ('wslb', models.IntegerField(null=True, verbose_name='文书类型')),
                ('djl', models.IntegerField(default=1, verbose_name='点击量')),
                ('ajxx', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ajxx.Ajxx', verbose_name='案件信息')),
            ],
            options={
                'ordering': ['-fbsj'],
                'verbose_name': '裁判文书',
                'verbose_name_plural': '裁判文书',
            },
        ),
    ]
