# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpws', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpws',
            name='cid',
            field=models.CharField(default='fd8ac081be6345629c1023529b78e8ca', editable=False, max_length=100, verbose_name='cid'),
        ),
    ]
