# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpws', '0002_auto_20160913_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpws',
            name='cid',
            field=models.CharField(default='a1ae87856bb4490c8efc8a1e94416d12', editable=False, max_length=100, verbose_name='cid'),
        ),
    ]
