# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fyxx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='法院名称')),
            ],
            options={
                'verbose_name': '法院名称',
                'verbose_name_plural': '法院名称',
            },
        ),
        migrations.CreateModel(
            name='Gjlb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mc', models.CharField(max_length=20, verbose_name='干警类别名称')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '干警类别名称',
                'verbose_name_plural': '干警类别名称',
            },
        ),
        migrations.CreateModel(
            name='Gjxx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xm', models.CharField(default='', max_length=20, verbose_name='姓名')),
                ('zc', models.CharField(default='', max_length=20, verbose_name='职称')),
                ('dh', models.CharField(default='', max_length=13, verbose_name='电话')),
                ('imgurl', models.FileField(upload_to='images/%Y%m%d/', verbose_name='图片')),
                ('gjlb', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dzfy.Gjlb', verbose_name='干警类别名称')),
            ],
            options={
                'verbose_name': '干警信息',
                'verbose_name_plural': '干警信息',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wzlx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='文章类型')),
            ],
            options={
                'verbose_name': '文章类型',
                'verbose_name_plural': '文章类型',
            },
        ),
    ]
