# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzfy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fyxx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='法院名称')),
            ],
            options={
                'verbose_name': '法院名称',
                'verbose_name_plural': '法院名称',
            },
        ),
        migrations.CreateModel(
            name='Wzlx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='文章类型')),
            ],
            options={
                'verbose_name': '文章类型',
                'verbose_name_plural': '文章类型',
            },
        ),
    ]
