# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zxgk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ajlx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lx', models.CharField(max_length=20, verbose_name='案件类型')),
            ],
            options={
                'verbose_name': '案件类型',
                'verbose_name_plural': '案件类型',
            },
        ),
        migrations.CreateModel(
            name='Ajxx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('ah', models.CharField(max_length=50, verbose_name='案号')),
                ('cbfy', models.CharField(max_length=30, null=True, verbose_name='承办法院')),
                ('ajly', models.CharField(max_length=50, null=True, verbose_name='案件来源')),
                ('lasj', models.DateTimeField(verbose_name='立案时间')),
                ('ktsj', models.DateTimeField(null=True, verbose_name='开庭时间')),
                ('cbft', models.CharField(max_length=50, null=True, verbose_name='承办法庭')),
                ('zxay', models.TextField(max_length=500, null=True, verbose_name='执行案由')),
                ('zxyj', models.TextField(max_length=500, null=True, verbose_name='执行依据')),
                ('zxyjwsbh', models.CharField(max_length=200, null=True, verbose_name='文书编号')),
                ('sxfyjjg', models.CharField(max_length=100, null=True, verbose_name='生效法院及机关')),
                ('sqzxbd', models.FloatField(null=True, verbose_name='申请执行标的')),
                ('sxsj', models.DateTimeField(null=True, verbose_name='生效时间')),
                ('zxyjws', models.TextField(null=True, verbose_name='执行依据文书')),
                ('lxqk', models.TextField(max_length=200, null=True, verbose_name='履行情况')),
                ('aqjj', models.TextField(default='', max_length=500, null=True, verbose_name='案情简介')),
                ('ajlx', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ajxx.Ajlx', verbose_name='案件类型')),
                ('fgxx', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zxgk.Fgxx', verbose_name='承办人')),
            ],
            options={
                'ordering': ['-ktsj'],
                'verbose_name': '案件信息',
                'verbose_name_plural': '案件信息',
            },
        ),
    ]
