# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ajxx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(default='d96a2868d0354a2787ace5be574a8ee2', editable=False, max_length=100)),
                ('ah', models.CharField(max_length=50, verbose_name='案号')),
                ('ajly', models.CharField(max_length=50, null=True, verbose_name='案件来源')),
                ('lasj', models.DateTimeField(verbose_name='立案时间')),
                ('ktsj', models.DateTimeField(null=True, verbose_name='开庭时间')),
                ('cbft', models.CharField(max_length=50, null=True, verbose_name='承办法庭')),
                ('zxay', models.TextField(max_length=500, null=True, verbose_name='执行案由')),
                ('zxyj', models.TextField(max_length=500, null=True, verbose_name='执行依据')),
                ('zxyjwsbh', models.CharField(max_length=200, null=True, verbose_name='文书编号')),
                ('sxfyjjg', models.CharField(max_length=100, null=True, verbose_name='生效法院及机关')),
                ('sqzxbd', models.FloatField(null=True, verbose_name='申请执行标的')),
                ('sxsj', models.DateTimeField(null=True, verbose_name='生效时间')),
                ('zxyjws', models.TextField(null=True, verbose_name='执行依据文书')),
                ('lxqk', models.TextField(max_length=500, null=True, verbose_name='履行情况')),
            ],
            options={
                'verbose_name_plural': '案件信息',
                'ordering': ['-ktsj'],
                'verbose_name': '案件信息',
            },
        ),
    ]
