# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zxgk', '0002_auto_20160913_1515'),
        ('ajxx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajxx',
            name='fgxx',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='zxgk.Fgxx'),
        ),
        migrations.AlterField(
            model_name='ajxx',
            name='aid',
            field=models.CharField(default='67d20f6d6b4f4ceea2ba2ec00e2f8e82', editable=False, max_length=100),
        ),
    ]
