# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajxx', '0002_auto_20160913_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajxx',
            name='cbfy',
            field=models.CharField(max_length=30, null=True, verbose_name='承办法院'),
        ),
        migrations.AlterField(
            model_name='ajxx',
            name='aid',
            field=models.CharField(default='49eb930d911649c684233b59e81a6f07', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='ajxx',
            name='fgxx',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='zxgk.Fgxx', verbose_name='承办人'),
        ),
    ]
