# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajxx', '0003_auto_20160913_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajxx',
            name='aid',
            field=models.CharField(default='a774be62bbfd4db4a2fdaccfba4def88', editable=False, max_length=100),
        ),
    ]
