# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajxx', '0004_auto_20160914_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajxx',
            name='aid',
            field=models.CharField(default='5a432f997d764ae28db163243fb9a904', editable=False, max_length=100),
        ),
    ]
